# This is a templated file and must be kept up-to-date with the original
# from upstream at https://github.com/canonical/se-tooling-ci-common.
name: Run Tests
on:
  workflow_call:
    inputs:
      test-input:
        required: true
        type: string

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.8', '3.10', '3.12']
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        exclude:
          - os: ubuntu-20.04
            python-version: '3.10'
          - os: ubuntu-20.04
            python-version: '3.12'
          - os: ubuntu-22.04
            python-version: '3.8'
          - os: ubuntu-22.04
            python-version: '3.12'
          - os: ubuntu-24.04
            python-version: '3.8'
          - os: ubuntu-24.04
            python-version: '3.10'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Test input value
      run: |
        echo "Input value: ${{ inputs.test-input }}"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r gh-test-requirements.txt
    - name: Test with tox
      run: tox -e py3
    - name: Run pylint
      run: tox -e pylint
      if: matrix.python-version == '3.10'
    - name: Run pep8
      run: tox -e pep8
      if: matrix.python-version == '3.10'
    - name: Build docs
      run: tox -e docs
      if: matrix.python-version == '3.10'
    - uses: actions/upload-artifact@v4
      with:
        name: documentation-preview
        path: doc/build
